### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by aresgow100** [ixopay/pgc-woocommerce#2]
Hi,

I have wordpress website with woocommerce on it, and we are working with a bank that just started working with ixopay and no one knows what should i do to implement it.
I installed the 1.7.0 plugin on my wordpress website following the read me text and it cant read the test cards, on every test card it says (cards for success and cards for failure) "Payment failed or was declined" and also there is nothing in woocommerce>status>logs.
Can you pls help me.

Thanks in advance.

**Comment by ohtyap** [comment]
We would need more information about your concrete scenario, merchant account und connector configuration. Public Github issues might not be the right place for such sensitive informations. Therefor please contact the IXOPAY support for further assistance.

**Comment by aresgow100** [comment]
Hi,

I tried contacting IXOPAY but no one answered me, can you pls tell me where to contact them?

Thanks in advance.
